plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

repository: rileywheadon/rileywheadon.github.io
domain: rileywheadon.github.io      
url: https://rileywheadon.github.io 
sass:
    sass_dir: _sass
